version: 2
workflows:
  version: 2
  dist-compile:
    jobs:
      - subete

jobs:
  subete:
    docker:
      - image: cimg/base:2021.01-20.04
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -y liblua5.3-dev lua-socket lua-sec python3-docutils cmake valgrind libxcb1-dev libyajl-dev libasound2-dev libglib2.0-dev libpulse-dev libudev-dev libnl-3-dev libnl-genl-3-dev libx11-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-util0-dev
      - run: cmake -DWITH_LUA_LIBRARY=lua5.3 -DBUILD_PLUGIN_PULSE=ON -DBUILD_PLUGIN_UNIXSOCK=ON .
      - run: make
      - run: ./tests/misc.sh .
      - run: ./tests/torture.sh .
      - run: PT_TOOL=valgrind PT_MAX_LAG=150 ./tests/pt.sh .
